### ISSUE TITLE
Plot functions in 1.2

### ISSUE THREAD

**Issue by rustylewis** [yangkky/BeBi-HW#2]
Make representative plots of each function.

**Comment by chigozienri** [comment]
Make plots interactive.

**Comment by chigozienri** [comment]
I do not understand what exactly is going on in the Hill function, it is very bizarre. I have explored it to the best of my ability, I think it is enough for the problem set.

Look at this strangeness, though: http://www.wolframalpha.com/input/?i=Plot+y+%3D+x%5Ea%2F%28%28-1%29%5Ea%2Bx%5Ea%29%3B
