### ISSUE TITLE
Bin sizes in 1.3

### ISSUE THREAD

**Issue by chigozienri** [yangkky/BeBi-HW#8]
Kevin changed the bins sizes to use linspace instead of arange, which makes sense, because then we can give a number of bins instead of a bin width. But why is there a "+ 100" in the maxima?
e.g. bins=np.linspace(min(df_tidy['time']), max(df_tidy['time']) + 100, 20)

**Comment by yangkky** [comment]
You had those in there before. I assumed they were to push the max value to a nice round number of something. I can take them out though. .

**Comment by chigozienri** [comment]
They were there in the arange because we want the maximum value in our list of bin boundaries to equal the maximum value of our data. Say we had data which ranged from 0 to 50 and we wanted bins of size 10. np.arange(0,50,10) would give us a list [0, 10, 20, 30, 40], so instead we want np.arange(0, 50+10, 10) which gives [0, 10, 20, 30, 40, 50]. I don't think it is necessary when you are using linspace, because np.linspace(0,50,6) already gives you bins of [  0.,  10.,  20.,  30.,  40.,  50.]

(And I must have accidentally used the value of +100 even when the bin widths were 50 and 200, which probably contributed to the confusion)

**Comment by yangkky** [comment]
That makes sense. I fixed it and pushed the commit.
